### ISSUE TITLE
Add mask to inputs

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#107]
We need mask on your inputs, especially number inputs. Please make sure it plays nice with `react-hook-form`

Eg: 
* 1000000000 => 100,000,000
* 12345.67 => 12,345.67

**Comment by lalitkumawat1m** [comment]
Could You Please explain more about this issue?

**Comment by dahal** [comment]
I think @chetannn is working on this. Essentially we want to implement mask on input, meaning when users type something like

123456789 it automatically appears as 123,456,789 (thousands), so its easier to read. Here is an example for a vanilla js 
https://imask.js.org/

**Comment by chetannn** [comment]
Yep. I am on it already. Just need to raise the PR.

**Comment by dahal** [comment]
Closed by PR #127
