### ISSUE TITLE
Stakeholder table is not responsive

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#108]
![2024-02-07 00 36 35](https://github.com/opencapco/opencap.co/assets/3684236/f30dbe0d-5ffc-44be-8024-0bf99439e46e)

**Comment by Vinyl-Davyl** [comment]
from where can this stake holders table be reached? there's only a landing page from what i see

**Comment by dahal** [comment]
> from where can this stake holders table be reached? there's only a landing page from what i see

Please follow the instruction on readme to setup the project. Here is the link to that stakeholder/member table
https://github.com/opencapco/opencap.co/blob/23acaec130a4c74a2156276affbb2fd74cece889/src/components/stakeholder/member-table.tsx

And this how its currently rendered
https://github.com/opencapco/opencap.co/blob/23acaec130a4c74a2156276affbb2fd74cece889/src/app/(authenticated)/(dashboard)/%5BpublicId%5D/stakeholders/page.tsx#L41-L43

**Comment by lalitkumawat1m** [comment]
Can I work on this issue?

**Comment by lalitkumawat1m** [comment]
May I work on this issue?

**Comment by dahal** [comment]
Sure thing @lalitkumawat1m please feel free to submit a PR.
