### ISSUE TITLE
Add one or many stakeholders

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#137]
* Add one or many stakeholders

* We already have stakeholder model defined on schema.prisma
https://github.com/opencapco/opencap.co/blob/be7fc50142c14d68ac924dcd430dc5c2868ae42b/prisma/schema.prisma#L154-L175

* We can just implement a xl or 2xl (size) modal with [React Spreadsheet](https://iddan.github.io/react-spreadsheet/) library to add one or many at the same time.
https://github.com/opencapco/opencap.co/blob/be7fc50142c14d68ac924dcd430dc5c2868ae42b/src/components/shared/modal.tsx#L31

**Comment by dahal** [comment]
> correct me if I understand this wrong hai dai,
> 
> * There is already a model created in the prisma.schema
>   `model Stakeholder {...}`
> * Code for creating stakeholders is not built yet and I have to make this feature right?
> * To do so, I first have to add a button somewhere in the :id/stakeholders  page and Add Stakeholders button and a modal will show up, then there will be an option for adding a stakeholder or add multiple stakeholders and the same time.
> * Then I have to create Trpc procedures and stuffs to handle this request, right?
> 
> so could you explain me a little but about the 3rd point you mentioned? I didn't quite understand it fully, why do we need to use ReactSpreadsheet library to add Stakeholders?
> 
> couldn't we just use normal html forms? please explain this part to me. and also it would be nice to have a UI design.

Great questions @Aashish-Upadhyay-101 
- Usually there will be bunch of stakeholders so having a single form to add them one at a time is not a good idea.

So I recommend one of two solutions:-
1. We could go with the a textarea and uploader where they can copy/paste or upload csv but we have to enforce some rules around headers, perhaps we can give them a sample csv, have them download it, format data as according to the csv and copy/paste of upload.
2. Another one would be to use React Spreadsheet to bulk copy paste and format within the interface.

Now that I think about it, option #1 could be a good approach for now.

**Comment by dahal** [comment]
Re: UI - unfortunately we do not have a designer on the team just yet. If you know anybody who wants to contribute to an OSS project, please invite them.

**Comment by Aashish-Upadhyay-101** [comment]
and one more thing @dahal dai, 
correct me if I say anything wrong,

so now I understand the issue, I will talk about how I am gonna implement this feature: 
- in the frontend:
    -  an XL or 2xl size modal with the option to import CSV and a textarea to manually enter the values in a CSV format.
    - a table to display all the current stakeholders.
- the backend should handle the following:
    * a CSV parser both for files and textarea
    * create trpc router for stakeholder
    * create procedures for creating a stakeholder
        - `inviteStakeholder` similar to `inviteMembers` 
        - Zod schemas and stuff
        - handling database operations
        - A quick question: This part's implementation would be similar to that of `inviteMember` procedure, right?
    * also other procedures like `remoteStakeholder`, `revoke-invites`, etc similar to `members`, right?

**Comment by dahal** [comment]
> and one more thing @dahal, correct me if I say anything wrong,
> 
> so now I understand the issue, I will talk about how I am gonna implement this feature:
> 
> * in the frontend:
>   
>   * an XL or 2xl size modal with the option to import CSV and a textarea to manually enter the values in a CSV format.
>   * a table to display all the current stakeholders.
> * the backend should handle the following:
>   
>   * a CSV parser both for files and textarea
>   * create trpc router for stakeholder
>   * create procedures for creating a stakeholder
>     
>     * `inviteStakeholder` similar to `inviteMembers`
>     * Zod schemas and stuff
>     * handling database operations
>     * A quick question: This part's implementation would be similar to that of `inviteMember` procedure, right?
>   * also other procedures like `remoteStakeholder`, `revoke-invites`, etc similar to `members`, right?

Correct, for now lets not implement the invite, remove, reinvite features. Stakeholder for now will not have access to login. We will implement login and stakeholder RBAC on V2. Just modal with bulk upload (textarea, csv import) and table to render the stakeholders should be good enought.

**Comment by dahal** [comment]
Resolved by #142
