### ISSUE TITLE
Complete profile edit feature

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#139]
We currently have a UI designed for profile page. If you navigate to `[publicId]/profile` you will see this UI

![CleanShot 2024-02-22 at 00 55 44](https://github.com/opencapco/opencap.co/assets/3684236/436f8ad3-6764-4851-8a8c-e7b218819f1e)

We have not created trpc and hooked it up with ui to complete the feature yet. We need to implement that.

We already have file uploader helper which will help us upload file to s3 compatible bucket. Its currently being used by `Uploader.tsx` to upload documents. We need to implement similar feature to upload avatar image.

Please note that, these profile images will be public, so they need a different bucket. Make sure to create and use a different bucket for this and add it to the env variable `PUBLIC_UPLOAD_BUCKET`.

**Comment by Raju-kadel-27** [comment]
@dahal Can you assign this to me. I want to work on it ?

**Comment by dahal** [comment]
Its all yours @Raju-kadel-27, I have assigned it to you.

**Comment by Raju-kadel-27** [comment]
@dahal @chetannn I think it's ready for review.

**Comment by dahal** [comment]
This is done on #150
