### ISSUE TITLE
Create securities > options page with table and multi-step form

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#173]
Issue

* Currently Securities > Options page is empty

Solution

* We want to render a table with list of all current options (issued)
* Create a multi-step form to collect all the options information based on the schema. (we already have schema defined for `option` model/table on `schema.prisma`

This UI for a multi-step form looks really good, let's go with similar design. Please take a look at `activity-card` for this design for left hand side steps

[https://dribbble.com/shots/22382839-Multi-form-step](https://dribbble.com/shots/22382839-Multi-form-step)

![CleanShot 2024-03-05 at 00 22 02](https://uploads.linear.app/80757c07-e84a-4969-ba5c-4915ce54e143/66b9120a-d55e-4b36-8338-6532818d32bc/8a4736a3-4e32-4564-b0e8-a7211428db95?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwNzU3YzA3LWU4NGEtNDk2OS1iYTVjLTQ5MTVjZTU0ZTE0My82NmI5MTIwYS1kNTVlLTRiMzYtODMzOC02NTMyODE4ZDMyYmMvOGE0NzM2YTMtNGUzMi00NTY0LWIwZTgtYTcyMTE0MjhkYjk1IiwiaWF0IjoxNzA5NjE5ODg2LCJleHAiOjMzMjgwMTc5ODg2fQ.bOtigX3DCiMyZiLPBrCl9ajkXt0wliYkPzp9mVDcQYU)

**Comment by Raju-kadel-27** [comment]
@dahal Can you please assign this to me ??

**Comment by dahal** [comment]
> @dahal Can you please assign this to me ?? Does we need a modal for multi-step-form or ??

Sure, please give it a shot and submit a PR. Modal with multi-step-form, similar UI as above would be great. @Aashish-Upadhyay-101 is working on #172 and that will have the same UI/flow, so please collaborate with him.

**Comment by dahal** [comment]
Here are the steps and input fields for this form

General details
  - Grant ID: eg: ISO-1, NSO-2 etc (create a grandId column, unique per company)
  - Grant type
  - Quantity
  - Status

Vesting details
  - Vesting schedule
  - Equity plan
  - Exercise price
  - Stakeholder

Relevant Dates
  - Issue date
  - Expiry date
  - Vesting start date
  - Board approval date
  - Rule 144 date

Documents
  - Drag and drop uploader (allow multiple files)

**Comment by dahal** [comment]
Resolved by Raju on this PR #180
