### ISSUE TITLE
Switching between the company seems to be broken

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#174]
![switching-company](https://github.com/opencapco/opencap.co/assets/3684236/b454bc2b-c059-4241-a10d-d14f1b721857)

**Comment by anikdhabal** [comment]
hey @dahal this issue is fixed by this pr- https://github.com/opencapco/opencap.co/pull/161

**Comment by dahal** [comment]
> hey @dahal this issue is fixed by this pr- #161

Oh sweet, let me know when its ready for a review. @anikdhabal

**Comment by anikdhabal** [comment]
> > hey @dahal this issue is fixed by this pr- #161
> 
> Oh sweet, let me know when its ready for a review. @anikdhabal

It's ready for review now.
