### ISSUE TITLE
Add existing SAFEs with table and multi-step form

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#177]
Issue

* Currently Securities > Safe page is empty

Solution

* We want to render a table with list of all current safe
* Please use datatable to render the SAFE, it already has pagination, search and filters. (Take a look at Settings > Team for reference)
* CTA button should be a drop down button and should say `Add a SAFE`
* Drop down options are `Add existing SAFE` and `Create a new SAFE`
* Create a multi-step form to collect all the existing SAFE information based on the schema. (we already have schema defined for `safe` model/table on `schema.prisma`
* Steps are going to to be pretty much the same as #178 except, we are not going to ask users to pick a "SAFE template" and no Signing required, instead we should allow multiple document uploads.

![CleanShot 2024-03-26 at 00 23 15](https://github.com/opencapco/opencap.co/assets/3684236/d757ef4f-9b10-4126-b56c-5a4706c12f43)

**Comment by Raju-kadel-27** [comment]
@dahal  can you please assign this to me ?? I want to take this.

**Comment by dahal** [comment]
> @dahal can you please assign this to me ?? I want to take this.

Please complete #180 and you can work on it.

**Comment by Raju-kadel-27** [comment]
@dahal I am working on it now.

**Comment by dahal** [comment]
Thanks for your interest @Raju-kadel-27. This issue is currently blocked by #178, I will wrap that up soon and it'll be open for contribution.

**Comment by Tarunkumartasets** [comment]
@Raju-kadel-27  please let me know if i can help in any possible way for development

**Comment by dahal** [comment]
Now that we have a foundation build for new SAFE, this issue is open to contribution.

**Comment by mustajab-ikram** [comment]
Hey @dahal, Can I work on this please?

**Comment by dahal** [comment]
I believe @Raju-kadel-27 is already working on this, please let us know if this issue is open for @mustajab-ikram to contribute.

**Comment by Raju-kadel-27** [comment]
@mustajab-ikram Yes, this issue is almost done. Please find other interesting issue you like.
