### ISSUE TITLE
Create a new SAFE with YC template and custom template

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#178]
* I have already created schema, and a multi-step modal for this feature to get started with

![CleanShot 2024-03-19 at 01 53 50](https://github.com/opencapco/opencap.co/assets/3684236/62068056-1ff9-4d63-834e-feaa0f16ec9a)

* Please implement all the following (steps are on comment) input fields and steps.
* YC SAFEs are currently on `public/yc` directory.
* If user has picked from one of these templates, remove the document step, if they have picked `CUSTOM` as an option on `SAFE template` selector, show them the document step.

If they have picked YC template
* Upload the template to their document repository (Upload on a private bucket)
* Redirect them to `/:publicId/templates/:documentId` so they can configure the template for eSign

![CleanShot 2024-03-19 at 02 01 44](https://github.com/opencapco/opencap.co/assets/3684236/0922185c-5ca8-4b3f-8484-5f89b4a95603)

If they have picked `CUSTOM` during `SAFE template` selector
* Show the documents step
* Do not allow `multiple = {false}`
* Title should be, `Upload the custom SAFE template`
* After the upload, redirect them to `/:publicId/templates/:documentId`

> Note: this PR is not going to do any esigning features/fixes.

> ~eSign is currently being worked on by @G3root~ - Complete for this use case
> ~Multi-step modal is being worked on by @Aashish-Upadhyay-101~ - Complete

**Comment by dahal** [comment]
Here are the steps and labels for multi step form

General information
  - Safe ID
  - YC SAFE type or other
  - Discount rate
  - Pro-rata rights

Additional information
  - Valuation cap
  - Investment amount
  - Issue date
  - Board approval date

Investor information
  - Select investor
  - Or add new investor

Sign and send to investor
  - Use YC SAFE template
  - Or upload custom template

**Comment by dahal** [comment]
Raju is going to pick this up. Thanks @Raju-kadel-27

**Comment by Raju-kadel-27** [comment]
@dahal can you assign this issue to me ?
