### ISSUE TITLE
Upload company logo

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#209]
![CleanShot 2024-03-23 at 03 05 26](https://github.com/opencapco/opencap.co/assets/3684236/7f0beda4-8172-4ce7-a97e-45855c6eda14)

Change company logo has not been implemented yet. Please go to setting page to find this page.

Implementation can can be something similar to `settings > profile > Change avatar`

**Comment by Vinyl-Davyl** [comment]
Would like to work on this issue can you assign

**Comment by dahal** [comment]
> Would like to work on this issue can you assign

Thanks for picking this up @Vinyl-Davyl , I have assigned it to you 🙏🏼

**Comment by dahal** [comment]
Due it inactivity, I am making it open for others to contribute. Please feel free to submit the PR.

**Comment by anikdhabal** [comment]
Please assign this issue to me. I will fix it quickly.

**Comment by mustajab-ikram** [comment]
Hi @anikdhabal , would you mind if I take over this issue? It would really help me gain familiarity with the codebase? This would be my first issue in openCap. Hope you understand.
Thanks
