### ISSUE TITLE
We need Error boundaries and need to handle exceptions

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#210]
We need to render error pages for bunch of errors (404, 500 etc).

Also, let's implement sentry for exception notifications. We donot want to be vendor locked, so lets make sure that the code does not break if Sentry is not enabled.

**Comment by Vinyl-Davyl** [comment]
Would like to work on this too

**Comment by dahal** [comment]
> Would like to work on this too

Assigned 🚀

**Comment by dahal** [comment]
Due it inactivity, I am making it open for others to contribute. Please feel free to submit the PR.

**Comment by Tarunkumartasets** [comment]
this is not_found page  for 404 
![image](https://github.com/opencapco/opencap.co/assets/159755287/4f4e878e-b875-4abe-ac7a-adde2a845287)
in next 14 we need to have each error.tsx as they have removed 500.tsx which was in page router 


doubt's
@dahal  should we make sentry integration optional 
@dahal  can I get some idea to standardised the way we show error in each pages
also do we need to add error boundary to each major component 

progress
404 page is done 
sentry integration is done

**Comment by dahal** [comment]
@Pranavtej looks like @Tarunkumartasets picked this up, we have other issues if any of it interests you 🙏🏼


@Tarunkumartasets for error pages, let's go with something simple, I'll post a mockup shortly.

**Comment by dahal** [comment]
@Tarunkumartasets 

- please make it optional
- lets use the mockup above for all 404 pages
- lets go with this [approach](https://maxschmitt.me/posts/nextjs-404-page-app-router)

**Comment by DIWAKARKASHYAP** [comment]
@dahal i raised this PR due it inactivity
