### ISSUE TITLE
Create a trpc backend API for file uploads.

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#24]
* TRPC backend API could use Cloudflare R2 for uploads for now (internally we will use that). We need to make this configurable somehow for those wanting to self host and use S3, GCP or any other platform.

Update, @topboyasante already created the `Uploader` components on #28, now we just need the endpoint
* ~This component could support both drag and drop interface and input uploads. Ideally would be nice to provide props to activate one or the other.~
* ~We will use different buckets for different types of uploads, so perhaps pass `uploadType` as prop. For example: `avatar, companyLogo, incorporationDocument` etc.~

**Comment by topboyasante** [comment]
Hi. I have zero experience with TRPC, but i can builld the upload component. can i pick this issue up?

**Comment by dahal** [comment]
@topboyasante absolutely, we can separate this task into two, one for component and another for TRPC backend endpoint. Please send a PR, if that look promising, I will create a diff issue for TRPC part.

**Comment by topboyasante** [comment]
sure

**Comment by topboyasante** [comment]
@dahal How many files should a user be able to upload at a go?

**Comment by dahal** [comment]
> @dahal How many files should a user be able to upload at a go?

We can make that configurable as well.

**Comment by topboyasante** [comment]
sure. submitted a PR.

**Comment by dahal** [comment]
Will continue on #31
