### ISSUE TITLE
Need help with email templates design for magic login link and user invite to join a company.

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#25]
Let's use [react.email](https://react.email/) with tailwind. This component library looks promising.

* https://www.reactemailtemplate.com/

**Comment by G3root** [comment]
I'm open to this. Is it okay to use https://jsx.email/ which is a fork of react.email

**Comment by dahal** [comment]
> I'm open to this. Is it okay to use https://jsx.email/ which is a fork of react.email but better

That sounds good, I have not checked out jsx.email yet, if that supports tailwind (our contributors are mostly familiar with), I think we can go with that. Looking at your draft, it looks promising. Lets go 🚀
