### ISSUE TITLE
Login with google using next/auth

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#30]
Signup/login page has Continue with Google, but its not implemented. We just need to implement this

https://next-auth.js.org/providers/google

**Comment by topboyasante** [comment]
hi. Kindly assign this task to me. thanks

**Comment by dahal** [comment]
@topboyasante thanks for your interest on this PR. Please send a PR, or a draft and it will be assigned to you.

**Comment by topboyasante** [comment]
Sure. Can i get the `clientId` and `clientSecret` keys?

**Comment by topboyasante** [comment]
hi @dahal, I've set up OAuth with google, but i get some this `OAuthAccountNotLinked` error after signing in. I have very little experience with prisma, and I think the problem is from the signIn callback function i've written. I'm creating a PR so you can take a look.
