### ISSUE TITLE
Invite team/stakeholder

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#35]
* Find or create a user account
* A modal with email, job title, and access (dropdown) to select their `Membership#access` refer to Membership model (schema) for `MEMBERSHIP_ACCESS`, `Membership#status` should be pending at this point.
* Using next-auth, [dub.sh does this really well](https://github.com/dubinc/dub/blob/main/apps/web/ui/modals/invite-teammate-modal.tsx), lets reverse engineer it. create a magic link and send an invitation email using `MemberInviteEmail` template.
* They donot need onboarding, so set `isOnboarded` to `true`
* Upon accepting invitation, update the `Membership#status` to accepted.
* Create a table similar to one you see on screenshot. Table ideally should include Name, email, title, access, with three tabs on top, Active, Pending, Inactive.
* Create an Edit action with this icon [https://remixicon.com/icon/edit-line](https://remixicon.com/icon/edit-line), options should be, Update, Off-board, Re-invite (if its on Pending tab)
* Create trpc endpoints for all of the above (Update, Off-board, Re-invite) and connect them to UI.

Basically its going to be a complete feature.

Invite modal

![CleanShot 2024-01-15 at 23.19.44.png](https://uploads.linear.app/80757c07-e84a-4969-ba5c-4915ce54e143/6d81a7aa-09ed-41cc-8826-09001655a627/4f7f849b-3f43-4d99-a143-0e2aa279802b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwNzU3YzA3LWU4NGEtNDk2OS1iYTVjLTQ5MTVjZTU0ZTE0My82ZDgxYTdhYS0wOWVkLTQxY2MtODgyNi0wOTAwMTY1NWE2MjcvNGY3Zjg0OWItM2Y0My00ZDk5LWExNDMtMGUyYWEyNzk4MDJiIiwiaWF0IjoxNzA1Mzg0NjM2LCJleHAiOjMzMjc1OTQ0NjM2fQ.1WpaiaEeGRk-vPAwimob2QuMWNwXEt-ved1EZm-asjE "=999x")

Team / Stakeholder UI

![CleanShot 2024-01-15 at 23.33.48.png](https://uploads.linear.app/80757c07-e84a-4969-ba5c-4915ce54e143/3ad0932e-c309-4e46-8b85-2969e8a06a4f/b675f863-802a-4cb8-bdc5-cefae1faad27?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwNzU3YzA3LWU4NGEtNDk2OS1iYTVjLTQ5MTVjZTU0ZTE0My8zYWQwOTMyZS1jMzA5LTRlNDYtOGI4NS0yOTY5ZThhMDZhNGYvYjY3NWY4NjMtODAyYS00Y2I4LWJkYzUtY2VmYWUxZmFhZDI3IiwiaWF0IjoxNzA1Mzg0NjM2LCJleHAiOjMzMjc1OTQ0NjM2fQ.ZghgH0KjS8I_d1tbHjXSaNa44oYk-7X2sijCcZdvBOc "=942x")

**Comment by G3root** [comment]
picking this up
