### ISSUE TITLE
Horizontal Scroll on Landing page

### ISSUE THREAD

**Issue by biomathcode** [opencapco/opencap.co#6]
### Current Website as viewed on Windows, Chrome.

Issue: Horizontal Scroll appears

BrowserStack, or LambdaTest can be use to reproduce the issue.

![Windows-11 (1)](https://uploads.linear.app/80757c07-e84a-4969-ba5c-4915ce54e143/5633569a-8417-4a14-acd0-8c199036461b/64beb3c0-0636-47dd-9a89-d132cd946cb9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwNzU3YzA3LWU4NGEtNDk2OS1iYTVjLTQ5MTVjZTU0ZTE0My81NjMzNTY5YS04NDE3LTRhMTQtYWNkMC04YzE5OTAzNjQ2MWIvNjRiZWIzYzAtMDYzNi00N2RkLTlhODktZDEzMmNkOTQ2Y2I5IiwiaWF0IjoxNzA0OTgxNjY2LCJleHAiOjMzMjc1NTQxNjY2fQ.FzvGcy_gbrFLmrGZDHFrn56qsO7G4uTmG66QCZaeceA)

**Comment by tedspare** [comment]
Fixed by #7
