### ISSUE TITLE
Implement stakeholder update, invite and deactivate feature.

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#71]
This PR #70 is rendering stakeholders on table. @G3root had previously implemented some Reinvite and remove stakeholder feature. We will re-use some of those but what we really want to accomplish with this are as follows:-

1. Only `admin` should be able to add, update, re-invite and deactivate stakeholders.
2. `admin` should not be allowed to deactivate their own account (for now)
3. Deactivate should only update `membership => active` status to false.

![CleanShot 2024-01-25 at 22 49 08](https://github.com/opencapco/opencap.co/assets/3684236/e5c73966-2eb3-46d2-9062-0b46375f8e52)

**Comment by G3root** [comment]
Picking this up
