### ISSUE TITLE
Improve stakeholder invite flow

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#79]
We currently add `invitedEmail` on `Membership` table when inviting new stakeholder. Instead of that

* Find or create a user account based on the email address provided.
* Send them login link (magic link) by creating a `VerificationToken` which we already do.
* Redirect them to a verification page, where they can verify their name and email address.
* When clicking continue, set `Membership#status` to `accepted`

**Comment by ksushant6566** [comment]
Picking this up :)

**Comment by ksushant6566** [comment]
Hey sorry, something came up and I couldn't get to it.

I will get to it over this weekend but please feel free to assign this to someone else in case this is urgent :)

**Comment by dahal** [comment]
Weekend

> Hey sorry, something came up and I couldn't get to it.
> 
> I will get to it over this weekend but please feel free to assign this to someone else in case this is urgent :)

No worries @ksushant6566 this weekend should work. Thanks 🚀

**Comment by ksushant6566** [comment]
> We currently add `invitedEmail` on `Membership` table when inviting new stakeholder. Instead of that
> 
> * Find or create a user account based on the email address provided.
> * Send them login link (magic link) by creating a `VerificationToken` which we already do.
> * Redirect them to a verification page, where they can verify their name and email address.
> * When clicking continue, set `Membership#status` to `accepted`

Hey @dahal , quick question regarding point 3, 
 - verify name: this means that the name given at the time of inviting should be prefilled and the user should be able to update it, right?
 
 - Wdym by user can verify their email? if the user is at this screen doesn't this mean that their email is verified?
 
 This 👇 is the current verification page

<img width="1241" alt="image" src="https://github.com/opencapco/opencap.co/assets/50081688/8e839c86-732b-4421-8e4c-49f0c0512404">

**Comment by dahal** [comment]
> > We currently add `invitedEmail` on `Membership` table when inviting new stakeholder. Instead of that
> > 
> > * Find or create a user account based on the email address provided.
> > * Send them login link (magic link) by creating a `VerificationToken` which we already do.
> > * Redirect them to a verification page, where they can verify their name and email address.
> > * When clicking continue, set `Membership#status` to `accepted`
> 
> Hey @dahal , quick question regarding point 3,
> 
> * verify name: this means that the name given at the time of inviting should be prefilled and the user should be able to update it, right?
> * Wdym by user can verify their email? if the user is at this screen doesn't this mean that their email is verified?
> 
> This 👇 is the current verification page
> 
> <img alt="image" width="1241" src="https://private-user-images.githubusercontent.com/50081688/302124245-8e839c86-732b-4421-8e4c-49f0c0512404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDk1NDIsIm5iZiI6MTcwNzEwOTI0MiwicGF0aCI6Ii81MDA4MTY4OC8zMDIxMjQyNDUtOGU4MzljODYtNzMyYi00NDIxLThlNGMtNDlmMGMwNTEyNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA1MDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWRjMWNmNTI3MWE5MmJkMWZlYjAwZTNmNzg3NjI3NTkyMGQ0MmU2MGM2YzE0YWJmMjE2NDJmNjQ5ZTkzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWk79NqEwEkGYJtZdM7M8sIgcRZf1nrpslAz2BIIKJY">

The reason I mentioned email is because we wanted to introduce two emails

* login email (could be personal email, employees/stakeholders can use even after they leave the company)
* work email.

Lets go ahead a do that on this PR, might as well right? Lets have workEmail on membership table and ask user to provide that email while they land on this verification page. @ksushant6566

**Comment by dahal** [comment]
I have create an issue for `workEmail` as well #95

**Comment by ksushant6566** [comment]
Makes sense, I'll add this
