### ISSUE TITLE
Start tracking audits/events

### ISSUE THREAD

**Issue by dahal** [opencapco/opencap.co#90]
Please note that these are going to be tracked on `audit` table. We already have a lib called `audit` for this. One additional column we need on this audit table is `summary`, which will have a human friendly message

Eg: 
`John Doe invited Will Smith as an admin`
`Will Smith accepted an invitation to join Company X`

Here are few places we can add these events/logs to:
* Signup
* Company create
* Stakeholder invite
* Stakeholder re-invite
* Stakeholder accept
* Stakeholder update
* Stakeholder remove

**Comment by G3root** [comment]
Picking this up
